---
language: node_js

node_js:
  - 0.10

branches:
  except:
  - gh-pages

env:
  matrix:
    - TEST=unit
#    - TEST=sauce

before_script:
#  - if [ "x$TEST" == "xsauce" ]; then curl -L https://gist.githubusercontent.com/santiycr/5139565/raw/sauce_connect_setup.sh | bash; fi
  - npm install -g gulp

script:
  - gulp --require LiveScript test:$TEST
